### ISSUE TITLE
wubi_embedding

### ISSUE THREAD

**Issue by Rainysunnyday** [A-Rain/NER-with-wubi-embedding-and-iterative-learning#1]
您好，我想请问一下，那个五笔嵌入是如何得到的呀。

**Comment by Wh1isper** [comment]
五笔编码表 实际上这个提升比较一般_(:з」∠)_



---Original---

**Comment by Rainysunnyday** [comment]
aha 那您模型中主要使用的不是五笔嵌入么 ^^

**Comment by Wh1isper** [comment]
这是一个创新点，另一个创新点是数据集上的
五笔嵌入确实有些作用，但也不算惊人。我有看到其他领域使用词性和词典（词匹配特征）的，提升好像还不如五笔嵌入哈哈
这是一篇比较篇实用性的论文，模型方面的创新我觉得并不值得吹~
毕竟被BERT虐了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yvonne Yang"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 晚上7:58
收件人: "A-Rain/NER-with-wubi-embedding-and-iterative-learning"<NER-with-wubi-embedding-and-iterative-learning@noreply.github.com&gt;; 
抄送: "Wh1isper"<9573586@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [A-Rain/NER-with-wubi-embedding-and-iterative-learning] wubi_embedding (#1)





 
aha 那您模型中主要使用的不是五笔嵌入么 ^^

**Comment by A-Rain** [comment]
您好，模型中使用了五笔嵌入，用于增强字的表示， @Wh1isper 也已经回答的比较详细了。五笔嵌入也在很多论文中有使用过，比如：
1. Multiple Character Embeddings for Chinese Word Segmentation
2. Character-level Chinese-English Translation through ASCII Encoding
您也可以参考下这些文章。

**Comment by Rainysunnyday** [comment]
嗯嗯嗯 非常感谢您们的解答 我再仔细看看~
